import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import EdgeLinesSmart from "@/components/EdgeLinesSmart"; // <- ok importar client aqui

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* começa na 2ª seção marcada (Hero é index 0, sem linhas) */}
        <EdgeLinesSmart startIndex={1} hideBelowWidth={1279} />
        {children}
      </body>
    </html>
  );
}
